#%RAML 1.0
title: DeliveryApi.
protocols: [http,https]
/Deliver:
  post:
    description: create an account for deliver service
    queryParameters:
      custname:
        type: string
        description: name on the address to be delivered
        required: true
      custaddress:
        description: the address where the package will be delivered
        type: string
        example: 123 abcst
        required: true
        enum: [home ,work ]
      custcity:
        type: string
        required: true
      custstate:
        type: string
        required: true
      custzipcode:
        type: integer
        required: true

          
      
      
  get:
  put:
  /{deliveryid}:
    get:
/Customer:
  post:
  get:
  /{customerid}:
    get: