#%RAML 1.0
title: DeliveryApi.
protocols: [http,https]
traits:
  ErrorResponce: !include trait.raml
/Delivery:
  post:
    description: create an account for deliver service
   
    body:
      application/json:
        example: !include example/delivExample.raml
         
    responses:
      201:
        body:
          application/json:
            example:
              {
                meg: account created successfully
              }
  is:
    - ErrorResponce
  get:
    description: fetch customer account
    body:
      application/json:
        example: !include example/delivExample.raml
          
    responses:
      201:
        body:
          application/json:
            example:
              {
                meg: successfully retrived
              }
    is:
      - ErrorResponce
  put:
    description: update delivery and customer account 
    queryParameters:
      updatedate:
        type: date-only
        required: false
      updatetime:
        type: datetime
        required: false
      deliverymanid:
        type: integer
        required: false
    body:
      application/json:
        example:
          {
            "updatedate" : 2021-12-12,
            "updatetime" : 11:15 am ,
            "deliverymanid" : 12344
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                meg : update successfull
              }
    is:
      - ErrorResponce 

/Customer:
  post:
    description: creat a new customer account for delivery
    queryParameters:
      username:
        type: string
        required: true
      e-mailadd: 
        type: string
        required: true
    body:
      application/json:
        example: !include example/customerexample.raml
         
    responses:
      201:
        body:
          application/json:
            example:
              {
                "userid" : 12345
              }
  is:
    - ErrorResponce
  /{customerid}:
    get:
      description: fetch customer id
      body:
        application/json:
          example: !include example/customerexample.raml 
           
      responses:
        201:
          body:
            application/json:
              example:
                {
                  userid : 12345
                }
    is:
      - ErrorResponce      
  
