#%RAML 1.0
title: DeliveryApi.
protocols: [http,https]
/Deliver:
  post:
    description: create an account for deliver service
    queryParameters:
      custname:
        type: string
        
  get:
  put:
  /{deliveryid}:
    get:
/Customer:
  post:
  get:
  /{customerid}:
    get: