#%RAML 1.0 Library
usage: !include deliveryapi.raml
securitySchemes:
  adminsecurity: !include security/oauthsecurityScheme.raml
  custsecurity: !include security/basicsecurityScheme.raml
types:
  delivdata: !include data file/deliverydataType.raml
  customerdata: !include data file/custdataType.raml
  adminputdata: !include data file/adminPutdataType.raml
traits:
  messageResponce: !include trait.raml
