#%RAML 1.0 ResourceType
  201:
    body:
      application/json:
        example:
          {
        meg: created successfully
          }
  200:
    body:
      application/json:
        example:
          {
        meg: ok
          }