#%RAML 1.0 Trait
responses:
  401:
    body:
      application/json:
        example:
          {
           meg : anauthorized request
          }
  404:
    body:
      application/json:
        example:
          {
           meg : 
          }
  500:
    body:
      application/json:
        example:
          {
           meg : anauthorized request
          }
