#%RAML 1.0 DataType
properties:
  username:
    type: string
    required: true
  e-mailadd: 
    type: string
    required: true
  custpassword:
    type: string
    required : true
  custadd:
    type: string
    required: true
  phonenumb:
    type: integer
    required: true


